steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-todo-app', '-f', 'Dockerfile', 'my-todo-app']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-todo-app']

  # Step 3: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'my-todo-service',
      '--image', 'gcr.io/$PROJECT_ID/my-todo-app',
      '--region', 'europe-west1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080'
    ]

# Specify the images to be pushed
images:
  - 'gcr.io/$PROJECT_ID/my-todo-app'
